### ISSUE TITLE
SyntaxError: Unexpected token 'I', "Invalid Au"... is not valid JSON

### ISSUE THREAD

**Issue by TBD** [pomdtr/deno-lastlogin#1]
using smallweb/vscode 0.1.1 and last login setup from readme I get

```
SyntaxError: Unexpected token 'I', "Invalid Au"... is not valid JSON
    at parse (<anonymous>)
    at packageData (ext:deno_fetch/22_body.js:408:14)
    at consumeBody (ext:deno_fetch/22_body.js:261:12)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async VSCode.fetchHandler (https://jsr.io/@pomdtr/lastlogin/0.5.11/mod.ts:243:32)
    at async file:///home/smallweb/.cache/smallweb/sandbox/NdBbZd7tkWaYREWlHYqlQ34TJkUBRltlanAw1UiBnt0=.ts:44:30
    at async mapped (ext:deno_http/00_serve.ts:384:18)
```

**Comment by pomdtr** [comment]
fixed in latest version
